# Generated by Django 5.1.7 on 2025-03-12 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='Category',
            new_name='category',
        ),
    ]
