# Generated by Django 5.1.7 on 2025-03-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_income_budget_remove_expense_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
